services:
  - type: web
    name: shibau-trading-platform
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true