services:
  - type: web
    name: shibau-trading-platform
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
    healthCheckPath: /
    autoDeploy: true